language: python
services:
  - docker
addons:
  apt:
    packages:
    - ldap-utils
    - python-ldap
virtualenv:
    system_site_packages: true
script:
    - docker build -t apacheds-test .
    - docker run -d --name apacheds-test -p 10389:10389 apacheds-test
    - sleep 10
    - echo "Old style"
    - bin/initialize
    - bin/group public add
    - bin/user public add
    - bin/user public in public
    - bin/search
    - yes | bin/clear
    - echo "New style"
    - bin/ldapo --apply init
    - bin/ldapo --apply user public --password public
    - bin/ldapo --apply group public --member public
    - bin/ldapo search 'uid=public'
    - docker rm -f apacheds-test
