language: python
services:
  - docker
addons:
  apt:
    packages:
    - ldap-utils
script:
    - docker build -t apacheds-test .
    - docker run -d --name apacheds-test -p 10389:10389 apacheds-test
    - sleep 10
    - bin/initialize
    - bin/group public add
    - bin/user public add
    - bin/user public in public
    - bin/search
    - yes | bin/clear
    - docker rm -f apacheds-test
